# Generated by Django 4.2.2 on 2023-07-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_uuidsession_emailreserve"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailreserve",
            name="social",
            field=models.URLField(blank=True),
        ),
    ]
