# Generated by Django 3.2.2 on 2022-03-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'verbose_name': 'mission', 'verbose_name_plural': 'missions'},
        ),
        migrations.AlterModelOptions(
            name='missionperson',
            options={'verbose_name': 'mission person', 'verbose_name_plural': 'mission persons'},
        ),
        migrations.AlterModelOptions(
            name='missionsubmission',
            options={'verbose_name': 'mission submission', 'verbose_name_plural': 'mission submissions'},
        ),
        migrations.AlterModelOptions(
            name='missionvisualization',
            options={'verbose_name': 'mission visualizatiom', 'verbose_name_plural': 'mission visualizations'},
        ),
        migrations.AlterModelOptions(
            name='missionvisualizationinstance',
            options={'verbose_name': 'mission visualization instance', 'verbose_name_plural': 'mission visualization instances'},
        ),
        migrations.AlterField(
            model_name='mission',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='media/missions/content/', verbose_name='attachment'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='day',
            field=models.DateField(verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='description',
            field=models.TextField(default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='title',
            field=models.CharField(max_length=256, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='missionperson',
            name='uid',
            field=models.UUIDField(verbose_name='uid'),
        ),
        migrations.AlterField(
            model_name='missionsubmission',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='media/missions/submissions/', verbose_name='attachment'),
        ),
        migrations.AlterField(
            model_name='missionsubmission',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='missionsubmission',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='missionsubmission',
            name='name',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='missionvisualizationinstance',
            name='seen_at',
            field=models.DateTimeField(editable=False, verbose_name='seen_at'),
        ),
    ]
