# Generated by Django 3.2.2 on 2022-05-01 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_auto_20220320_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('start_date', models.DateTimeField(verbose_name='start_date')),
                ('end_date', models.DateTimeField(verbose_name='end_date')),
            ],
            options={
                'verbose_name': 'mission class',
                'verbose_name_plural': 'mission classes',
            },
        ),
        migrations.AddField(
            model_name='mission',
            name='for_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='missions.missionclass'),
        ),
        migrations.AddField(
            model_name='missionperson',
            name='on_class',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='missions.missionclass'),
        ),
    ]
