# Generated by Django 3.2.2 on 2022-05-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0006_alter_missionperson_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='for_class',
        ),
        migrations.AddField(
            model_name='mission',
            name='for_class',
            field=models.ManyToManyField(blank=True, related_name='missions', to='missions.MissionClass', verbose_name='for class'),
        ),
        migrations.RemoveField(
            model_name='missionperson',
            name='on_class',
        ),
        migrations.AddField(
            model_name='missionperson',
            name='on_class',
            field=models.ManyToManyField(blank=True, related_name='persons', to='missions.MissionClass', verbose_name='on class'),
        ),
    ]
