# Generated by Django 3.2.2 on 2022-03-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0005_auto_20210520_2221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name': 'social link', 'verbose_name_plural': 'social links'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('M', 'master'), ('P', 'patron'), ('D', 'doer'), ('N', 'nothing')], default='N', max_length=1, verbose_name='type'),
        ),
    ]
