name: Python + Poetry

on:
  push:
    branches: [ refactor ]
  pull_request:
    branches: [ refactor ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Setup a local virtual environment (if no poetry.toml file)
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - name: Install the project dependencies
        run: poetry install
      - name: Run the automated tests (for example)
        run: poetry run poe t
        env:
          DJANGO_SECRET_KEY: test
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Initialize tailwind dependencies
        run: npm install
      - name: Compile tailwind files
        run: poetry run poe tw
      - name: Collect static files
        run: poetry run poe cs
        env:
          DJANGO_ENV: production
          DJANGO_DEBUG: 0
          DJANGO_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DJANGO_CSRF_TRUSTED_ORIGINS: "*"
          PUBLIC_ROOT: "public/"
      - name: Generate req file
        run: poetry export -f requirements.txt --output requirements.txt
      - name: Create "new" dir on remote
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          script: |
            mkdir -p test.engajaflix.club/new
      - name: Push to live site
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          source: "core/*,engajaflix_club/*,public/*,templates/*,manage.py,requirements.txt"
          target: "test.engajaflix.club/new"
      - name: Set correct files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          script: |
            cd test.engajaflix.club/new
            echo "" > .env
            echo "PUBLIC_ROOT=$(pwd)/public" >> .env
            echo "DJANGO_SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
            echo "DJANGO_ENV=production" >> .env
            echo "DJANGO_DEBUG=" >> .env
            echo "DJANGO_ALLOWED_HOSTS=engajaflix.club,www.engajaflix.club" >> .env
            echo "DJANGO_CSRF_TRUSTED_ORIGINS=https://*.engajaflix.club" >> .env
            echo "DJANGO_SUPERUSER_USERNAME=${{ secrets.SUPERUSER_USERNAME }}" >> .env
            echo "DJANGO_SUPERUSER_PASSWORD=${{ secrets.SUPERUSER_PASSWORD }}" >> .env
            echo "SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}" >> .env
            echo "SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> .env
            echo "ADMIN_URL=/admin/" >> .env
            echo "DATABASE_URL=${{ secrets.REFACTOR_DATABASE_URL }}" >> .env
            source ../venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate --noinput
            python manage.py makesuperuser
            cd ../
            cp -r new/* .
            rm -rf new
            touch tmp/restart.txt